"""
Atlas AI Models - Database entities for the persistent learning system
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone


def utcnow():
    return datetime.now(timezone.utc).isoformat()


# ============ USER LEARNING PROFILE ============

class UserLearningProfile(BaseModel):
    user_id: str
    overall_level: str = "unknown"  # unknown, beginner, intermediate, advanced, expert
    crypto_level: int = 0       # 0-10
    finance_level: int = 0
    blockchain_level: int = 0
    trading_level: int = 0
    risk_management_level: int = 0
    learning_goals: List[str] = []
    interests: List[str] = []
    preferred_learning_pace: str = "normal"  # slow, normal, fast
    preferred_explanation_style: str = "analogies"  # analogies, technical, examples, visual
    confidence_score: float = 0.0  # 0.0 - 1.0
    onboarding_completed: bool = False
    created_at: str = Field(default_factory=utcnow)
    updated_at: str = Field(default_factory=utcnow)

    def to_mongo(self):
        d = self.model_dump()
        d["updated_at"] = utcnow()
        return d

    @classmethod
    def from_mongo(cls, doc):
        if not doc:
            return None
        doc.pop("_id", None)
        return cls(**doc)


# ============ ATLAS MEMORY ============

class AtlasMemory(BaseModel):
    id: str = Field(default_factory=lambda: str(__import__('uuid').uuid4()))
    user_id: str
    memory_type: str  # fact, preference, struggle, strength, goal, interaction
    content: str
    importance: str = "normal"  # low, normal, high, critical
    source: str = "conversation"  # conversation, quiz, onboarding, system
    created_at: str = Field(default_factory=utcnow)
    updated_at: str = Field(default_factory=utcnow)
    expires_at: Optional[str] = None

    def to_mongo(self):
        return self.model_dump()

    @classmethod
    def from_mongo(cls, doc):
        if not doc:
            return None
        doc.pop("_id", None)
        return cls(**doc)


# ============ ATLAS CONVERSATION ============

class AtlasConversation(BaseModel):
    id: str = Field(default_factory=lambda: str(__import__('uuid').uuid4()))
    user_id: str
    title: str = "Nouvelle conversation"
    messages: List[Dict[str, str]] = []  # [{role, content}]
    created_at: str = Field(default_factory=utcnow)
    updated_at: str = Field(default_factory=utcnow)

    def to_mongo(self):
        d = self.model_dump()
        d["updated_at"] = utcnow()
        return d

    @classmethod
    def from_mongo(cls, doc):
        if not doc:
            return None
        doc.pop("_id", None)
        return cls(**doc)


# ============ LEARNING MODULE ============

class LearningModule(BaseModel):
    id: str = Field(default_factory=lambda: str(__import__('uuid').uuid4()))
    user_id: str
    title: str
    description: str = ""
    level: str = "beginner"  # beginner, intermediate, advanced
    category: str = "general"  # crypto, blockchain, trading, defi, security, etc.
    learning_objective: str = ""
    status: str = "not_started"  # not_started, in_progress, completed, mastered
    mastery_score: float = 0.0  # 0.0 - 100.0
    content: str = ""  # The lesson content (generated by Atlas)
    prerequisites: List[str] = []  # module IDs
    weak_areas: List[str] = []
    attempt_count: int = 0
    created_at: str = Field(default_factory=utcnow)
    updated_at: str = Field(default_factory=utcnow)
    last_reviewed_at: Optional[str] = None

    def to_mongo(self):
        d = self.model_dump()
        d["updated_at"] = utcnow()
        return d

    @classmethod
    def from_mongo(cls, doc):
        if not doc:
            return None
        doc.pop("_id", None)
        return cls(**doc)


# ============ MODULE PROGRESS ============

class ModuleProgress(BaseModel):
    id: str = Field(default_factory=lambda: str(__import__('uuid').uuid4()))
    module_id: str
    user_id: str
    progress_percentage: float = 0.0
    mastery_score: float = 0.0
    concepts_understood: List[str] = []
    concepts_weak: List[str] = []
    last_quiz_score: float = 0.0
    best_quiz_score: float = 0.0
    review_required: bool = False
    last_activity_at: str = Field(default_factory=utcnow)
    updated_at: str = Field(default_factory=utcnow)

    def to_mongo(self):
        d = self.model_dump()
        d["updated_at"] = utcnow()
        return d

    @classmethod
    def from_mongo(cls, doc):
        if not doc:
            return None
        doc.pop("_id", None)
        return cls(**doc)


# ============ QUIZ ATTEMPT ============

class QuizAttempt(BaseModel):
    id: str = Field(default_factory=lambda: str(__import__('uuid').uuid4()))
    user_id: str
    module_id: str
    questions_count: int = 0
    correct_answers: int = 0
    score: float = 0.0
    answers: List[Dict[str, Any]] = []
    difficulty: str = "normal"
    created_at: str = Field(default_factory=utcnow)

    def to_mongo(self):
        return self.model_dump()

    @classmethod
    def from_mongo(cls, doc):
        if not doc:
            return None
        doc.pop("_id", None)
        return cls(**doc)
