import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Dimensions, ActivityIndicator, Alert, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import * as Linking from 'expo-linking';
import { useAuthStore } from '../../store/authStore';
import { useTranslation } from '../../store/languageStore';
import { vipAPI } from '../../utils/api';

const API = process.env.EXPO_PUBLIC_BACKEND_URL || 'https://mentova-api.onrender.com';
const { width } = Dimensions.get('window');

const tr = {
  fr: {
    title: 'Mentova VIP',
    subtitle: 'Passe au niveau supérieur',
    founderTitle: 'Prix Fondateur',
    founderDesc: 'Pour les 500 premiers abonnés seulement',
    founderBadge: 'Badge Fondateur Exclusif',
    founderBadgeDesc: 'Un badge permanent et unique visible dans toute la communauté. Jamais reproduit.',
    priceFounder: '9,99',
    priceRegular: '25,99',
    perMonth: '/ mois',
    spotsLeft: 'places fondateur restantes',
    regularPrice: 'Prix régulier après les 500 premiers',
    feat1: 'Daily Briefing IA',
    feat1d: 'Résumé quotidien des marchés généré par Atlas IA, adapté à ton portefeuille et tes intérêts.',
    feat2: 'Accès illimité Atlas & IA',
    feat2d: 'Utilisation illimitée d\'Atlas (mentor IA) et de l\'IA avec screenshots. Sans VIP: 5 messages/jour.',
    feat3: 'Badge VIP',
    feat3d: 'Statut visible dans toute la communauté. Les membres VIP sont mis en avant dans les discussions.',
    feat4: 'Messages directs aux mentors',
    feat4d: 'Contacte directement les mentors certifiés par message privé pour du mentorat personnalisé.',
    cta: 'Devenir VIP Fondateur',
    ctaRegular: 'Devenir VIP',
    already: 'Tu es déjà VIP !',
    alreadyDesc: 'Profite de tous tes avantages exclusifs.',
    activeFeatures: 'Tes avantages actifs',
    guarantee: 'Prix verrouillé à vie tant que l\'abonnement est actif',
    cancel: 'Annulable à tout moment, sans engagement',
  },
  en: {
    title: 'Mentova VIP',
    subtitle: 'Level up your crypto game',
    founderTitle: 'Founder Price',
    founderDesc: 'For the first 500 subscribers only',
    founderBadge: 'Exclusive Founder Badge',
    founderBadgeDesc: 'A permanent and unique badge visible across the entire community. Never replicated.',
    priceFounder: '9.99',
    priceRegular: '25.99',
    perMonth: '/ month',
    spotsLeft: 'founder spots remaining',
    regularPrice: 'Regular price after the first 500',
    feat1: 'Daily IA Briefing',
    feat1d: 'Daily market summary generated by Atlas AI, adapted to your portfolio and interests.',
    feat2: 'Unlimited Atlas & AI',
    feat2d: 'Unlimited use of Atlas (AI mentor) and AI with screenshots. Without VIP: 5 messages/day.',
    feat3: 'VIP Badge',
    feat3d: 'Visible status across the community. VIP members are highlighted in discussions.',
    feat4: 'Direct messages to mentors',
    feat4d: 'Contact certified mentors directly via private message for personalized mentoring.',
    cta: 'Become VIP Founder',
    ctaRegular: 'Become VIP',
    already: 'You are already VIP!',
    alreadyDesc: 'Enjoy all your exclusive benefits.',
    activeFeatures: 'Your active benefits',
    guarantee: 'Price locked for life as long as subscription is active',
    cancel: 'Cancel anytime, no commitment',
  },
  es: {
    title: 'Mentova VIP',
    subtitle: 'Sube de nivel en crypto',
    founderTitle: 'Precio Fundador',
    founderDesc: 'Solo para los primeros 500 suscriptores',
    founderBadge: 'Insignia Fundador Exclusiva',
    founderBadgeDesc: 'Una insignia permanente y unica visible en toda la comunidad. Nunca replicada.',
    priceFounder: '9,99',
    priceRegular: '25,99',
    perMonth: '/ mes',
    spotsLeft: 'lugares fundador restantes',
    regularPrice: 'Precio regular despues de los primeros 500',
    feat1: 'Briefing IA Diario',
    feat1d: 'Resumen diario de mercados generado por Atlas IA, adaptado a tu portafolio e intereses.',
    feat2: 'Atlas & IA ilimitados',
    feat2d: 'Uso ilimitado de Atlas (mentor IA) e IA con capturas. Sin VIP: 5 mensajes/dia.',
    feat3: 'Insignia VIP',
    feat3d: 'Estado visible en toda la comunidad. Los miembros VIP se destacan en las discusiones.',
    feat4: 'Mensajes directos a mentores',
    feat4d: 'Contacta directamente a mentores certificados por mensaje privado para mentoria personalizada.',
    cta: 'Ser VIP Fundador',
    ctaRegular: 'Ser VIP',
    already: 'Ya eres VIP!',
    alreadyDesc: 'Disfruta de todos tus beneficios exclusivos.',
    activeFeatures: 'Tus beneficios activos',
    guarantee: 'Precio bloqueado de por vida mientras la suscripcion este activa',
    cancel: 'Cancela cuando quieras, sin compromiso',
  },
};

export default function VipHubScreen() {
  const router = useRouter();
  const { user, token } = useAuthStore();
  const { language } = useTranslation();
  const t = tr[language as keyof typeof tr] || tr.en;
  const [spots, setSpots] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const isVip = user?.is_vip === true;

  useEffect(() => {
    fetch(`${API}/api/spots-remaining`).then(r => r.json()).then(d => {
      setSpots(d.remaining ?? 498);
      setLoading(false);
    }).catch(() => { setSpots(498); setLoading(false); });
  }, []);

  const handleCheckout = async () => {
    if (!user || !token) {
      Alert.alert(
        language === 'fr' ? 'Connexion requise' : language === 'es' ? 'Inicio de sesion requerido' : 'Login required',
        language === 'fr' ? 'Connecte-toi pour devenir VIP.' : language === 'es' ? 'Inicia sesion para ser VIP.' : 'Log in to become VIP.',
        [{ text: 'OK', onPress: () => router.push('/(tabs)/profile') }]
      );
      return;
    }

    setCheckoutLoading(true);
    try {
      const originUrl = Platform.OS === 'web'
        ? window.location.origin
        : API;

      const response = await vipAPI.createCheckout(originUrl);
      const { checkout_url } = response.data;

      if (checkout_url) {
        if (Platform.OS === 'web') {
          window.location.href = checkout_url;
        } else {
          await Linking.openURL(checkout_url);
        }
      }
    } catch (err: any) {
      const msg = err?.response?.data?.detail || (language === 'fr' ? 'Erreur lors du paiement' : 'Payment error');
      Alert.alert('Erreur', msg);
    } finally {
      setCheckoutLoading(false);
    }
  };

  const isFounderPrice = (spots ?? 0) > 0;

  const features = [
    { icon: 'newspaper' as const, color: '#3B82F6', title: t.feat1, desc: t.feat1d },
    { icon: 'planet' as const, color: '#7C3AED', title: t.feat2, desc: t.feat2d },
    { icon: 'diamond' as const, color: '#F59E0B', title: t.feat3, desc: t.feat3d },
    { icon: 'chatbubbles' as const, color: '#10B981', title: t.feat4, desc: t.feat4d },
  ];

  return (
    <SafeAreaView style={s.safe} edges={['top']}>
      {/* Header */}
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn} data-testid="vip-back">
          <Ionicons name="arrow-back" size={24} color="#FFF" />
        </TouchableOpacity>
        <Text style={s.headerTitle}>{t.title}</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView style={s.scroll} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>

        {/* Already VIP */}
        {isVip ? (
          <>
            <LinearGradient colors={['rgba(245,158,11,0.15)', 'rgba(245,158,11,0.05)']} style={s.alreadyCard}>
              <View style={s.alreadyIcon}>
                <Ionicons name="diamond" size={32} color="#FFD700" />
              </View>
              <Text style={s.alreadyTitle}>{t.already}</Text>
              <Text style={s.alreadyDesc}>{t.alreadyDesc}</Text>
            </LinearGradient>

            <Text style={s.sectionTitle}>{t.activeFeatures}</Text>
            {features.map((f, i) => (
              <View key={i} style={s.featureCard}>
                <View style={[s.featureIconWrap, { backgroundColor: f.color + '20' }]}>
                  <Ionicons name={f.icon} size={22} color={f.color} />
                </View>
                <View style={s.featureText}>
                  <Text style={s.featureTitle}>{f.title}</Text>
                  <Text style={s.featureDesc}>{f.desc}</Text>
                </View>
                <Ionicons name="checkmark-circle" size={22} color="#10B981" />
              </View>
            ))}
          </>
        ) : (
          <>
            {/* Hero */}
            <LinearGradient colors={['rgba(124,58,237,0.2)', 'rgba(59,130,246,0.1)']} style={s.hero}>
              <View style={s.heroIconRow}>
                <LinearGradient colors={['#B8860B', '#FFD700']} style={s.heroIcon}>
                  <Ionicons name="diamond" size={36} color="#000" />
                </LinearGradient>
              </View>
              <Text style={s.heroTitle}>{t.title}</Text>
              <Text style={s.heroSub}>{t.subtitle}</Text>
            </LinearGradient>

            {/* Pricing */}
            <View style={s.pricingCard}>
              {/* Founder Price */}
              {isFounderPrice && (
                <View style={s.founderBanner}>
                  <Ionicons name="flame" size={16} color="#FFD700" />
                  <Text style={s.founderBannerText}>{t.founderTitle}</Text>
                  <Ionicons name="flame" size={16} color="#FFD700" />
                </View>
              )}
              <View style={s.priceRow}>
                <Text style={s.priceCurrency}>$</Text>
                <Text style={s.priceAmount}>{isFounderPrice ? t.priceFounder : t.priceRegular}</Text>
                <Text style={s.pricePeriod}>{t.perMonth}</Text>
              </View>
              {isFounderPrice && (
                <>
                  <Text style={s.priceStrike}>${t.priceRegular}{t.perMonth}</Text>

                  {/* Counter */}
                  <View style={s.counterWrap}>
                    {loading ? <ActivityIndicator color="#FFD700" /> : (
                      <>
                        <View style={s.counterNumber}>
                          <Text style={s.counterValue}>{spots}</Text>
                        </View>
                        <Text style={s.counterLabel}>{t.spotsLeft}</Text>
                      </>
                    )}
                  </View>

                  {/* Progress bar */}
                  <View style={s.progressBg}>
                    <LinearGradient colors={['#B8860B', '#FFD700']} style={[s.progressFill, { width: `${((500 - (spots || 0)) / 500) * 100}%` }]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} />
                  </View>
                  <Text style={s.progressText}>{500 - (spots || 0)}/500</Text>
                </>
              )}
              {!isFounderPrice && <Text style={s.regularNote}>{t.regularPrice}</Text>}
            </View>

            {/* Founder Badge */}
            {isFounderPrice && (
              <LinearGradient colors={['rgba(184,134,11,0.15)', 'rgba(255,215,0,0.05)']} style={s.badgeCard}>
                <View style={s.badgeIconWrap}>
                  <LinearGradient colors={['#B8860B', '#FFD700']} style={s.badgeIcon}>
                    <Ionicons name="star" size={20} color="#000" />
                  </LinearGradient>
                </View>
                <View style={s.badgeTextWrap}>
                  <Text style={s.badgeTitle}>{t.founderBadge}</Text>
                  <Text style={s.badgeDesc}>{t.founderBadgeDesc}</Text>
                </View>
              </LinearGradient>
            )}

            {/* Features */}
            <Text style={s.sectionTitle}>{isFounderPrice ? t.founderDesc : ''}</Text>
            {features.map((f, i) => (
              <View key={i} style={s.featureCard}>
                <View style={[s.featureIconWrap, { backgroundColor: f.color + '20' }]}>
                  <Ionicons name={f.icon} size={22} color={f.color} />
                </View>
                <View style={s.featureText}>
                  <Text style={s.featureTitle}>{f.title}</Text>
                  <Text style={s.featureDesc}>{f.desc}</Text>
                </View>
              </View>
            ))}

            {/* CTA */}
            <TouchableOpacity
              style={[s.ctaWrap, checkoutLoading && { opacity: 0.6 }]}
              activeOpacity={0.85}
              onPress={handleCheckout}
              disabled={checkoutLoading}
              data-testid="vip-subscribe-btn"
            >
              <LinearGradient colors={['#B8860B', '#FFD700']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={s.ctaBtn}>
                {checkoutLoading ? (
                  <ActivityIndicator color="#000" size="small" />
                ) : (
                  <>
                    <Ionicons name="diamond" size={20} color="#000" />
                    <Text style={s.ctaText}>{isFounderPrice ? t.cta : t.ctaRegular}</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>

            {/* Guarantees */}
            <View style={s.guarantees}>
              <View style={s.guaranteeRow}>
                <Ionicons name="lock-closed" size={16} color="#10B981" />
                <Text style={s.guaranteeText}>{t.guarantee}</Text>
              </View>
              <View style={s.guaranteeRow}>
                <Ionicons name="shield-checkmark" size={16} color="#10B981" />
                <Text style={s.guaranteeText}>{t.cancel}</Text>
              </View>
            </View>
          </>
        )}

        <View style={{ height: 80 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#06060F' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.06)' },
  backBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.05)', alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '800', color: '#FFF' },
  scroll: { flex: 1 },
  content: { padding: 16 },

  // Hero
  hero: { borderRadius: 20, padding: 32, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(124,58,237,0.2)', marginBottom: 20 },
  heroIconRow: { marginBottom: 16 },
  heroIcon: { width: 72, height: 72, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  heroTitle: { fontSize: 28, fontWeight: '800', color: '#FFF', marginBottom: 6 },
  heroSub: { fontSize: 15, color: '#9CA3AF', textAlign: 'center' },

  // Pricing
  pricingCard: { backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,215,0,0.2)', borderRadius: 20, padding: 24, alignItems: 'center', marginBottom: 16 },
  founderBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(255,215,0,0.1)', paddingHorizontal: 16, paddingVertical: 6, borderRadius: 20, marginBottom: 16 },
  founderBannerText: { color: '#FFD700', fontSize: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  priceRow: { flexDirection: 'row', alignItems: 'flex-end', marginBottom: 4 },
  priceCurrency: { fontSize: 24, fontWeight: '700', color: '#FFD700', marginBottom: 8 },
  priceAmount: { fontSize: 56, fontWeight: '800', color: '#FFD700', lineHeight: 62 },
  pricePeriod: { fontSize: 16, color: '#9CA3AF', marginBottom: 10, marginLeft: 4 },
  priceStrike: { fontSize: 14, color: '#666', textDecorationLine: 'line-through', marginBottom: 20 },

  // Counter
  counterWrap: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  counterNumber: { backgroundColor: 'rgba(255,215,0,0.15)', borderWidth: 1, borderColor: 'rgba(255,215,0,0.3)', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 8 },
  counterValue: { fontSize: 28, fontWeight: '800', color: '#FFD700' },
  counterLabel: { color: '#9CA3AF', fontSize: 14, fontWeight: '600' },

  // Progress
  progressBg: { width: '100%', height: 6, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 3, overflow: 'hidden', marginBottom: 6 },
  progressFill: { height: 6, borderRadius: 3 },
  progressText: { color: '#666', fontSize: 12 },
  regularNote: { color: '#888', fontSize: 13, marginTop: 8 },

  // Founder Badge
  badgeCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: 'rgba(255,215,0,0.15)', marginBottom: 20, gap: 14 },
  badgeIconWrap: {},
  badgeIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  badgeTextWrap: { flex: 1 },
  badgeTitle: { color: '#FFD700', fontSize: 15, fontWeight: '700', marginBottom: 2 },
  badgeDesc: { color: '#9CA3AF', fontSize: 12, lineHeight: 18 },

  // Section
  sectionTitle: { color: '#888', fontSize: 13, fontWeight: '600', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.5 },

  // Features
  featureCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)', borderRadius: 16, padding: 16, marginBottom: 10, gap: 14 },
  featureIconWrap: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  featureText: { flex: 1 },
  featureTitle: { color: '#FFF', fontSize: 15, fontWeight: '700', marginBottom: 2 },
  featureDesc: { color: '#9CA3AF', fontSize: 12, lineHeight: 18 },

  // CTA
  ctaWrap: { marginTop: 8, marginBottom: 16 },
  ctaBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 16, borderRadius: 16 },
  ctaText: { fontSize: 17, fontWeight: '800', color: '#000' },

  // Guarantees
  guarantees: { gap: 10, marginTop: 4 },
  guaranteeRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  guaranteeText: { color: '#888', fontSize: 13 },

  // Already VIP
  alreadyCard: { borderRadius: 20, padding: 28, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(245,158,11,0.2)', marginBottom: 24 },
  alreadyIcon: { marginBottom: 12 },
  alreadyTitle: { fontSize: 22, fontWeight: '800', color: '#FFD700', marginBottom: 4 },
  alreadyDesc: { color: '#9CA3AF', fontSize: 14, textAlign: 'center' },
});
