import React, { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useAuthStore } from '../../store/authStore';
import { useTranslation } from '../../store/languageStore';

const API = process.env.EXPO_PUBLIC_BACKEND_URL || '';

const hubI18n: Record<string, Record<string, string>> = {
  'h.title': { fr: 'Espace VIP', en: 'VIP Hub', es: 'Espacio VIP' },
  'h.briefing': { fr: 'Briefing du jour', en: 'Daily Briefing', es: 'Briefing del dia' },
  'h.briefingDesc': { fr: 'Resume du marche genere par Atlas', en: 'Market summary generated by Atlas', es: 'Resumen del mercado generado por Atlas' },
  'h.loading': { fr: 'Generation en cours...', en: 'Generating...', es: 'Generando...' },
  'h.tools': { fr: 'Outils Pro', en: 'Pro Tools', es: 'Herramientas Pro' },
  'h.upgrade': { fr: 'Passez VIP pour debloquer', en: 'Upgrade to VIP to unlock', es: 'Pase a VIP para desbloquear' },
  'h.noData': { fr: 'Donnees indisponibles', en: 'Data unavailable', es: 'Datos no disponibles' },
  'h.sentiment': { fr: 'Sentiment', en: 'Sentiment', es: 'Sentimiento' },
  'h.events': { fr: 'Evenements cles', en: 'Key Events', es: 'Eventos clave' },
  'h.opportunity': { fr: 'Opportunite', en: 'Opportunity', es: 'Oportunidad' },
  'h.risk': { fr: 'Risque', en: 'Risk', es: 'Riesgo' },
  'h.btc': { fr: 'Bitcoin', en: 'Bitcoin', es: 'Bitcoin' },
  'h.eth': { fr: 'Ethereum', en: 'Ethereum', es: 'Ethereum' },
  'h.fearGreed': { fr: 'Fear & Greed', en: 'Fear & Greed', es: 'Fear & Greed' },
  'h.fearGreedDesc': { fr: 'Indice de peur et avidite du marche', en: 'Market fear and greed index', es: 'Indice de miedo y avidez del mercado' },
  'h.halving': { fr: 'Bitcoin Halving', en: 'Bitcoin Halving', es: 'Bitcoin Halving' },
  'h.halvingDesc': { fr: 'Compte a rebours du prochain halving', en: 'Next halving countdown', es: 'Cuenta regresiva del proximo halving' },
  'h.rainbow': { fr: 'Rainbow Chart', en: 'Rainbow Chart', es: 'Rainbow Chart' },
  'h.rainbowDesc': { fr: 'Zone de prix actuelle du Bitcoin', en: 'Bitcoin current price zone', es: 'Zona de precio actual de Bitcoin' },
  'h.alerts': { fr: 'Alertes Prix', en: 'Price Alerts', es: 'Alertas de Precio' },
  'h.alertsDesc': { fr: 'Creez des alertes personnalisees', en: 'Create custom alerts', es: 'Crea alertas personalizadas' },
  'h.wallet': { fr: 'Portefeuille Virtuel', en: 'Virtual Portfolio', es: 'Portafolio Virtual' },
  'h.walletDesc': { fr: 'Simulez vos investissements', en: 'Simulate your investments', es: 'Simula tus inversiones' },
  'h.chartAnalysis': { fr: 'Analyse de graphiques', en: 'Chart Analysis', es: 'Analisis de graficos' },
  'h.chartAnalysisDesc': { fr: 'Envoyez un graphique a Atlas', en: 'Send a chart to Atlas', es: 'Envia un grafico a Atlas' },
};

function th(key: string, lang: string): string {
  return hubI18n[key]?.[lang] || hubI18n[key]?.['en'] || key;
}

const TOOLS_LIST = [
  { id: 'briefing', icon: 'today', color: '#F59E0B' },
  { id: 'fearGreed', icon: 'speedometer', color: '#EF4444' },
  { id: 'halving', icon: 'timer', color: '#7C3AED' },
  { id: 'rainbow', icon: 'color-palette', color: '#10B981' },
  { id: 'chartAnalysis', icon: 'bar-chart', color: '#3B82F6' },
  { id: 'alerts', icon: 'notifications', color: '#F97316' },
  { id: 'wallet', icon: 'wallet', color: '#06B6D4' },
];

export default function VIPHubScreen() {
  const router = useRouter();
  const { token } = useAuthStore();
  const { language } = useTranslation();
  const lang = language || 'fr';
  const [permissions, setPermissions] = useState<any>(null);
  const [briefing, setBriefing] = useState<any>(null);
  const [briefingLoading, setBriefingLoading] = useState(false);
  const [fearGreed, setFearGreed] = useState<any>(null);
  const [halving, setHalving] = useState<any>(null);

  useEffect(() => {
    if (!token) return;
    fetch(`${API}/api/vip/permissions`, { headers: { Authorization: `Bearer ${token}` } })
      .then(r => r.json()).then(setPermissions).catch(() => {});
  }, [token]);

  const isVip = permissions?.is_vip;

  const loadBriefing = async () => {
    if (!isVip || briefingLoading) return;
    setBriefingLoading(true);
    try {
      const res = await fetch(`${API}/api/vip/daily-briefing?lang=${lang}`, { headers: { Authorization: `Bearer ${token}` } });
      const data = await res.json();
      if (data.success) setBriefing(data.data);
    } catch (e) { console.error(e); }
    finally { setBriefingLoading(false); }
  };

  const loadFearGreed = async () => {
    if (!isVip) return;
    try {
      const res = await fetch(`${API}/api/vip/tools/fear-greed`, { headers: { Authorization: `Bearer ${token}` } });
      const data = await res.json();
      if (data.success) setFearGreed(data.data);
    } catch (e) { console.error(e); }
  };

  const loadHalving = async () => {
    if (!isVip) return;
    try {
      const res = await fetch(`${API}/api/vip/tools/halving`, { headers: { Authorization: `Bearer ${token}` } });
      const data = await res.json();
      if (data.success) setHalving(data.data);
    } catch (e) { console.error(e); }
  };

  useEffect(() => {
    if (isVip) {
      loadBriefing();
      loadFearGreed();
      loadHalving();
    }
  }, [isVip]);

  if (!isVip) {
    return (
      <SafeAreaView style={s.container} edges={['top']}>
        <View style={s.header}>
          <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
            <Ionicons name="arrow-back" size={22} color="#fff" />
          </TouchableOpacity>
          <Text style={s.headerTitle}>{th('h.title', lang)}</Text>
          <View style={{ width: 40 }} />
        </View>
        <View style={s.lockedWrap}>
          <Ionicons name="lock-closed" size={48} color="#7C3AED" />
          <Text style={s.lockedText}>{th('h.upgrade', lang)}</Text>
          <TouchableOpacity style={s.upgradeBtn} onPress={() => router.push('/vip')}>
            <Ionicons name="diamond" size={16} color="#0A0A1A" />
            <Text style={s.upgradeBtnText}>VIP</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const sentimentColors: Record<string, string> = { bullish: '#10B981', bearish: '#EF4444', neutral: '#F59E0B' };
  const sentimentLabels: Record<string, Record<string, string>> = {
    bullish: { fr: 'Haussier', en: 'Bullish', es: 'Alcista' },
    bearish: { fr: 'Baissier', en: 'Bearish', es: 'Bajista' },
    neutral: { fr: 'Neutre', en: 'Neutral', es: 'Neutral' },
  };

  return (
    <SafeAreaView style={s.container} edges={['top']}>
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <Ionicons name="arrow-back" size={22} color="#fff" />
        </TouchableOpacity>
        <Text style={s.headerTitle}>{th('h.title', lang)}</Text>
        <View style={s.vipBadge}><Ionicons name="diamond" size={14} color="#FFD700" /></View>
      </View>

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
        {/* Daily Briefing */}
        <View style={s.section}>
          <View style={s.sectionHeader}>
            <Ionicons name="today" size={20} color="#F59E0B" />
            <Text style={s.sectionTitle}>{th('h.briefing', lang)}</Text>
          </View>
          {briefingLoading ? (
            <View style={s.loadingCard}><ActivityIndicator color="#7C3AED" /><Text style={s.loadingText}>{th('h.loading', lang)}</Text></View>
          ) : briefing ? (
            <View style={s.briefingCard} data-testid="daily-briefing-card">
              <Text style={s.briefingSummary}>{briefing.market_summary}</Text>
              <View style={s.sentimentRow}>
                <View style={[s.sentimentBadge, { backgroundColor: (sentimentColors[briefing.sentiment] || '#F59E0B') + '20' }]}>
                  <Ionicons name={briefing.sentiment === 'bullish' ? 'trending-up' : briefing.sentiment === 'bearish' ? 'trending-down' : 'remove'} size={14} color={sentimentColors[briefing.sentiment] || '#F59E0B'} />
                  <Text style={[s.sentimentText, { color: sentimentColors[briefing.sentiment] || '#F59E0B' }]}>
                    {sentimentLabels[briefing.sentiment]?.[lang] || briefing.sentiment}
                  </Text>
                </View>
              </View>
              {briefing.btc_analysis && <View style={s.briefingItem}><Text style={s.briefingLabel}>{th('h.btc', lang)}</Text><Text style={s.briefingValue}>{briefing.btc_analysis}</Text></View>}
              {briefing.eth_analysis && <View style={s.briefingItem}><Text style={s.briefingLabel}>{th('h.eth', lang)}</Text><Text style={s.briefingValue}>{briefing.eth_analysis}</Text></View>}
              {briefing.key_events?.length > 0 && (
                <View style={s.briefingItem}>
                  <Text style={s.briefingLabel}>{th('h.events', lang)}</Text>
                  {briefing.key_events.map((e: string, i: number) => (
                    <Text key={i} style={s.eventItem}>- {e}</Text>
                  ))}
                </View>
              )}
              {briefing.opportunity && <View style={s.briefingItem}><Text style={s.briefingLabel}>{th('h.opportunity', lang)}</Text><Text style={[s.briefingValue, { color: '#10B981' }]}>{briefing.opportunity}</Text></View>}
              {briefing.risk_alert && <View style={s.briefingItem}><Text style={s.briefingLabel}>{th('h.risk', lang)}</Text><Text style={[s.briefingValue, { color: '#EF4444' }]}>{briefing.risk_alert}</Text></View>}
            </View>
          ) : (
            <TouchableOpacity style={s.loadingCard} onPress={loadBriefing}>
              <Ionicons name="refresh" size={20} color="#7C3AED" />
              <Text style={s.loadingText}>{th('h.briefingDesc', lang)}</Text>
            </TouchableOpacity>
          )}
        </View>

        {/* Quick Stats: Fear & Greed + Halving */}
        <View style={s.quickRow}>
          <View style={s.quickCard}>
            <Ionicons name="speedometer" size={22} color="#EF4444" />
            <Text style={s.quickLabel}>{th('h.fearGreed', lang)}</Text>
            {fearGreed ? (
              <>
                <Text style={[s.quickValue, { color: parseInt(fearGreed.value) > 50 ? '#10B981' : '#EF4444' }]}>{fearGreed.value}</Text>
                <Text style={s.quickSub}>{fearGreed.label || fearGreed.value_classification}</Text>
              </>
            ) : <Text style={s.quickSub}>{th('h.noData', lang)}</Text>}
          </View>
          <View style={s.quickCard}>
            <Ionicons name="timer" size={22} color="#7C3AED" />
            <Text style={s.quickLabel}>{th('h.halving', lang)}</Text>
            {halving ? (
              <>
                <Text style={[s.quickValue, { color: '#7C3AED' }]}>{halving.days_remaining || '~'}j</Text>
                <Text style={s.quickSub}>{halving.estimated_date ? halving.estimated_date.substring(0, 10) : ''}</Text>
              </>
            ) : <Text style={s.quickSub}>{th('h.noData', lang)}</Text>}
          </View>
        </View>

        {/* Tools Grid */}
        <View style={s.section}>
          <Text style={s.sectionTitle}>{th('h.tools', lang)}</Text>
          <View style={s.toolsGrid}>
            {TOOLS_LIST.map(tool => (
              <TouchableOpacity
                key={tool.id}
                style={s.toolCard}
                onPress={() => {
                  if (tool.id === 'chartAnalysis') router.push('/(tabs)/learn');
                  else if (tool.id === 'briefing') loadBriefing();
                  else if (tool.id === 'rainbow') router.push('/(tabs)/market');
                }}
                data-testid={`vip-tool-${tool.id}`}
              >
                <View style={[s.toolIcon, { backgroundColor: tool.color + '15' }]}>
                  <Ionicons name={tool.icon as any} size={24} color={tool.color} />
                </View>
                <Text style={s.toolTitle}>{th(`h.${tool.id}`, lang)}</Text>
                <Text style={s.toolDesc} numberOfLines={2}>{th(`h.${tool.id}Desc`, lang)}</Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0A1A' },
  scroll: { paddingBottom: 40 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#1A1A2E' },
  backBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#1A1A2E', justifyContent: 'center', alignItems: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#fff' },
  vipBadge: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(255,215,0,0.12)', justifyContent: 'center', alignItems: 'center' },

  lockedWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40, gap: 16 },
  lockedText: { fontSize: 16, color: '#9CA3AF', textAlign: 'center' },
  upgradeBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FFD700', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 24 },
  upgradeBtnText: { fontSize: 15, fontWeight: '700', color: '#0A0A1A' },

  section: { paddingHorizontal: 16, marginTop: 20 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#E2E8F0', marginBottom: 12 },

  loadingCard: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#111128', borderRadius: 14, padding: 20, borderWidth: 1, borderColor: 'rgba(124,58,237,0.15)' },
  loadingText: { color: '#9CA3AF', fontSize: 13 },

  briefingCard: { backgroundColor: '#111128', borderRadius: 14, padding: 18, borderWidth: 1, borderColor: 'rgba(245,158,11,0.15)', gap: 12 },
  briefingSummary: { fontSize: 14, color: '#E2E8F0', lineHeight: 22 },
  sentimentRow: { flexDirection: 'row' },
  sentimentBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  sentimentText: { fontSize: 12, fontWeight: '700' },
  briefingItem: { borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.04)', paddingTop: 10 },
  briefingLabel: { fontSize: 12, fontWeight: '600', color: '#7C3AED', marginBottom: 4 },
  briefingValue: { fontSize: 13, color: '#9CA3AF', lineHeight: 19 },
  eventItem: { fontSize: 13, color: '#9CA3AF', lineHeight: 19 },

  quickRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, marginTop: 16 },
  quickCard: { flex: 1, backgroundColor: '#111128', borderRadius: 14, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.04)', gap: 6 },
  quickLabel: { fontSize: 12, fontWeight: '600', color: '#9CA3AF' },
  quickValue: { fontSize: 28, fontWeight: '800' },
  quickSub: { fontSize: 11, color: '#6B7280' },

  toolsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  toolCard: { width: '47%', backgroundColor: '#111128', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.04)' },
  toolIcon: { width: 42, height: 42, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  toolTitle: { fontSize: 13, fontWeight: '700', color: '#E2E8F0', marginBottom: 4 },
  toolDesc: { fontSize: 11, color: '#6B7280', lineHeight: 15 },
});
